### PR TITLE
feature: add ArchivePage

### PR DESCRIPTION
**Pull request by Ronald-TR**
Hi, first of all, thanks for building this interface for the Notion API!
I started using it and missed the "archive pages" feature, so i implemented it.

Cheers

### CODE REVIEW

**Comment by dstotijn** [comment]
Hi @Ronald-TR,

Glad to hear this package has been of use! As for the "Archive page" endpoint: While it exists, it's a deprecated endpoint; the [API docs](https://developers.notion.com/reference/archive-delete-a-page) state:

> "Please use the Update page endpoint to archive a page."

Similar to the "List databases" endpoint, I've deliberately decided _not_ to support deprecated endpoints in this library.
Thus I'm closing this PR, but thank you very much regardless for taking the time to open it.

**Comment by Ronald-TR** [comment]
HI, i think that we have a missunderstanding, haha. I didn't use the archive endpoit, but the pages endpoint itself. I'm just editing the body with the {'archived': true} content. But is the same /pages endpoint used.

**Comment by dstotijn** [comment]
Ah, gotcha. In that case, would you mind updating the PR to add an `Archived` field to [`UpdatePageParams`](https://github.com/dstotijn/go-notion/blob/5e7e8ed54c010b52edd2786fb50281b652c78321/page.go#L76) and update its [methods](https://github.com/dstotijn/go-notion/blob/5e7e8ed54c010b52edd2786fb50281b652c78321/page.go#L226-L249) to use this new field? If you could please rem remove the `Title` field, I added it by mistake probably because it doesn't seem to be supported (ref). You can also leave it and I can clean it up later.

This way, we can keep the existing [`UpdatePageProps`](https://github.com/dstotijn/go-notion/blob/master/client.go#L230), without the need for a separate method. The way I've modeled the `Client` struct, is that the methods are closely coupled to the API endpoints. Thanks again!

**Comment by Ronald-TR** [comment]
Cool, thanks for the insights, i will work on it asap!

**Pull request closed without merging**
